# Site settings
title: "WhatAKitty"
email: 104xuqiang@163.com
description: "一路走一路看"
baseurl: ""
url: "http://xuqiang.me"
title_description: "一路走一路看，人生的道路上有许多美妙的风景。"
title_image: "http://v1.qzone.cc/avatar/201512/02/20/40/565ee6d071e29733.jpg!200x200.jpg"
google_analytics: "UA-67857103-1"
disqus_account: yvoloshin
github_repository: https://github.com/WhatAKitty/
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: Dear君临
github_username: WhatAKitty
linkedin_link: 
google_plus_link: 
stackoverflow_link: http://stackoverflow.com/users/3165573/whitewater

# Footer
footer_left: "Template made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/Dear46673688\">Dear君临</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/WhatAKitty\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
